# Define variables in the datasets

# Target variables
TARGET_VAR1 = "HUFAMINC" # Family income
TARGET_VAR2 = "PRHRUSL" # Usual working hours

# ID variables
HOUSEHOLD_ID = "HRHHID"
PERSON_NUM = "HUHHNUM"

# Year variables
DATA_YEAR = "DATA_YEAR"
BIRTH_YEAR = "BIRTH_YEAR"
AGE = "PEAGE"

# Family variables
RELATIONSHIP = "PRFAMREL"
HAS_CHILD = "HAS_CHILD"
IS_REF_OR_SPOUSE = "IS_REF_OR_SPOUSE"
IS_CHILD = "IS_CHILD"
IS_OLDEST_CHILD = "IS_OLDEST_CHILD"
AGE_OF_OLDEST_CHILD = "AGE_OF_OLDEST_CHILD"
YEAR_OF_FIRST_BIRTH_GIVING = "YEAR_OF_FIRST_BIRTH_GIVING"

# Marriage variables
MARRITAL_STATUS = "PEMARITL"
IS_MARRIED = "IS_MARRIED"
MARRIAGE_TIMES = "MARRIAGE_TIMES"

# Demographic Variables
BIRTH_YEAR = BIRTH_YEAR
RACE = "PERACE"
GENDER = "PESEX"
EDUCATION = "PEEDUCA"
STATE = "GESTCEN"

COHORT_ID = "COHORT_ID"
# PSEUDO_ID = "PSEUDO_ID"

# Matching Variables
MATCHING_VARS = [BIRTH_YEAR, RACE, GENDER, EDUCATION, STATE]

# Variables needed for the analysis
NEEDED_VARS = [COHORT_ID, DATA_YEAR, # Data year
               BIRTH_YEAR, RACE, GENDER, EDUCATION, STATE, # Demographic variables
               AGE, IS_MARRIED, MARRITAL_STATUS, # Marriage variables
               HAS_CHILD, AGE_OF_OLDEST_CHILD, YEAR_OF_FIRST_BIRTH_GIVING, # Treatment variables
               TARGET_VAR1, TARGET_VAR2] # Target variables
               
