# Define variables in the datasets

# ID variables
HOUSEHOLD_ID = "HRHHID"
PERSON_NUM = "HUHHNUM"

# Year variables
DATA_YEAR = "DATA_YEAR"
BIRTH_YEAR = "BIRTH_YEAR"
AGE = "PEAGE"

# Family variables
RELATIONSHIP = "PRFAMREL"
HAS_CHILD = "HAS_CHILD"
IS_REF_OR_SPOUSE = "IS_REF_OR_SPOUSE"
IS_CHILD = "IS_CHILD"
IS_OLDEST_CHILD = "IS_OLDEST_CHILD"
AGE_OF_OLDEST_CHILD = "AGE_OF_OLDEST_CHILD"
YEAR_OF_FIRST_BIRTH_GIVING = "YEAR_OF_FIRST_BIRTH_GIVING"

# Marriage variables
MARRITAL_STATUS = "PEMARITL"
IS_MARRIED = "IS_MARRIED"
MARRIAGE_TIMES = "MARRIAGE_TIMES"

# Demographic Variables
BIRTH_YEAR = BIRTH_YEAR
RACE = "PERACE"
GENDER = "PESEX"
EDUCATION = "PEEDUCA"
STATE = "GESTCEN"

# Matching Variables
MATCHING_VARS = [BIRTH_YEAR, RACE, GENDER, EDUCATION, STATE]